name: Delete Stale Branches and Generate Report

on:
  workflow_dispatch:

jobs:
  delete-stale-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitpython openpyxl

      - name: Delete Stale Branches and Generate Report
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python -c "
          import os
          import openpyxl
          from github import Github
          from datetime import datetime, timedelta

          # GitHub authentication
          g = Github(os.getenv('GITHUB_TOKEN'))

          # Repository details
          org_name = 'HenrySchein-C'
          repo_name = 'GEPAngular'
          repo = g.get_repo(f'{org_name}/{repo_name}')

          # Define stale period (e.g., 6 months)
          stale_period = timedelta(days=180)
          now = datetime.utcnow()

          # Get all branches
          branches = repo.get_branches()

          # Prepare Excel workbook
          wb = openpyxl.Workbook()
          ws = wb.active
          ws.title = 'Deleted Branches'
          ws.append(['Branch Name', 'Last Commit Date'])

          # Identify and delete stale branches
          for branch in branches:
            branch_name = branch.name
            if branch_name == 'main' or branch_name == 'master':
                continue
            last_commit = repo.get_branch(branch_name).commit.commit.author.date
            if now - last_commit > stale_period:
                try:
                    ref = repo.get_git_ref(f'heads/{branch_name}')
                    ref.delete()
                    print(f'Deleted stale branch: {branch_name}')
                    ws.append([branch_name, last_commit.strftime('%Y-%m-%d')])
                except Exception as e:
                    print(f'Failed to delete branch {branch_name}: {e}')

          # Save the workbook
          wb.save('deleted_branches.xlsx')
          "

      - name: Upload Deleted Branches Report
        uses: actions/upload-artifact@v2
        with:
          name: deleted-branches-report
          path: deleted_branches.xlsx
