name: List Active Branches and Export to Excel

on:
  workflow_dispatch:

jobs:
  list-branches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: HenrySchein-C/HSCCV2Dev
        token: ${{ secrets.GH_TOKEN }}

    - name: Fetch all branches
      run: |
        git fetch --all

    - name: List all branches
      run: |
        git branch -r > all_branches.txt
        cat all_branches.txt

    - name: Filter active branches
      id: filter-branches
      run: |
        # Get current date and date 90 days ago
        current_date=$(date +%s)
        cutoff_date=$(date -d "-90 days" +%s)

        # Initialize an array
        active_branches=()

        # Read all branches
        while IFS= read -r branch; do
          branch_name=${branch##*/}
          
          # Remove 'origin/' prefix if present
          branch_name=${branch_name#origin/}

          # Skip HEAD references
          if [ "$branch_name" = "HEAD" ]; then
            continue
          fi

          # Check if the branch is active
          echo "Processing branch: $branch_name"
          if last_commit_date=$(git log -1 --format=%ct "origin/$branch_name" 2>/dev/null); then
            if [ "$last_commit_date" -ge "$cutoff_date" ]; then
              active_branches+=("$branch_name")
              echo "Branch '$branch_name' is active."
            else
              echo "Branch '$branch_name' is not active."
            fi
          else
            echo "Warning: Could not retrieve last commit date for branch '$branch_name'"
          fi

        done < all_branches.txt

        # Save active branches to a file
        printf "%s\n" "${active_branches[@]}" > active_branches.txt
        cat active_branches.txt

    - name: Convert to Excel
      run: |
        sudo apt-get install -y python3-pip
        pip3 install pandas openpyxl
        python3 -c "
        import pandas as pd

        # Read the list of active branches
        with open('active_branches.txt') as f:
            branches = [line.strip() for line in f.readlines()]

        # Create a DataFrame and save to Excel
        df = pd.DataFrame(branches, columns=['Active Branches'])
        df.to_excel('active_branches.xlsx', index=False)
        "

    - name: Upload Excel file
      uses: actions/upload-artifact@v2
      with:
        name: active-branches
        path: active_branches.xlsx
